[package]
name = "reward"
version = "0.1.0"
edition = "2024"

[env]
DATABASE_URL="postgresql://lenny:lenny@localhost:5432/reward"



[dependencies]
sea-orm = { version = "1.1.8", features = [ "sqlx-postgres","runtime-tokio-native-tls", "macros" ] }
actix-web = "4"
time = "0.3.41"
