[package]
name = "repositories"
version = "0.1.0"
edition = "2024"

[dependencies]
sea-orm = { workspace = true }
log = { workspace = true }
entity = { workspace = true }
common = { workspace = true }