[package]
name = "controller"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = { workspace = true }
service = { workspace = true }
entity = { workspace = true }
common = { workspace = true }
