//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::service_provider::Entity as ServiceProvider;
pub use super::user::Entity as User;
pub use super::user_fee::Entity as UserFee;
pub use super::user_relation::Entity as UserRelation;
pub use super::user_reward::Entity as UserReward;
