//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq,Serialize,Deserialize)]
#[sea_orm(table_name = "user_relation")]
pub struct Model {
    pub parent_id: i64,
    pub left: i32,
    pub right: i32,
    pub create_time: DateTime,
    pub level: i32,
    pub user_id: i64,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub service_provider_id:i64
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation,Serialize,Deserialize)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
